/**
 * Fixed aviation / NOTAM vocabulary for the Learn highlighter.
 * A token is ordinary shorthand when it is in this set (or a number, coordinate,
 * time, NOTAM id, runway/taxiway designator, or 1–3 letter abbreviation/ident).
 * Extend this list — do not grow it from live NOTAM text.
 *
 * Intentionally absent (so they paint red): crane, bird/birds, wildlife, drone,
 * festival, concert, balloon, and other non-phraseology words.
 */

const TERM_SOURCE = `
  100LL ABATEMENT ABEAM ABM ABNORMAL ABOUT ABOVE ABV ACC ACFT ACROSS ACTION ACTIVATED
  ACTIVE ACTIVITY AD ADDED ADDITIONAL ADDN ADF ADJ ADJACENT ADVISE ADVISED ADZ
  AERODROME AERODROMES AFTER AFTERNOON AGAINST AGL AIC AIDS AIP AIRAC AIRCRAFT AIRMET
  AIRPORT AIRPORTS AIRSPACE AIRWAY AIRWAYS ALL ALONG ALS ALSF ALSO ALT ALTERNATE ALTIM
  ALTIMETER ALTITUDE ALTITUDES ALTN AMDT AMEND AMENDED AMENDMENT AMENDMENTS AMONG AMSL
  AND ANNUAL ANTENNA ANY APCH APN APP APPROACH APPROACHES APPROVAL APPROVED APPROX
  APPROXIMATE APPROXIMATELY APR APRIL APRON APRONS APRX ARE AREA AREAS ARFF AROUND ARP
  ARPT ARR ARRIVAL ARRIVALS AS ASDA ASHTAM ASOS ASPHALT AT ATF ATIS ATTENTION ATTN ATZ
  AUG AUGUST AUTH AUTHORISED AUTHORIZED AUTUMN AVAILABILITY AVAILABLE AVBL AVGAS AVOID
  AWAY AWOS AWSS BACKCOURSE BANNER BARO BASE BAY BC BE BEEN BEFORE BEING BELOW BENEATH
  BETWEEN BEYOND BKN BLAST BLASTPAD BLDG BLO BLOCK BLW BOTH BR BRAKING BROKEN BTN
  BUILDING BUILDINGS BUTTON BY CABLE CALIBRATION CAN CANCEL CANCELED CANCELLED CANNOT
  CAT CAUTION CAUTIONED CAVOK CEILING CEILINGS CENTER CENTERLINE CENTRE CENTRELINE
  CHANGE CHANGED CHANGES CHANNEL CHART CHARTS CHECK CHECKED CHECKLIST CHECKLISTS CHECKS
  CHEMICAL CHG CHIMNEY CIG CIRCA CIRCLING CIRCUIT CIVIL CLASS CLEARANCE CLEARED
  CLEARING CLEARWAY CLEARWAYS CLIMB CLIMBING CLOSED CLOSURE CLOSURES CLOUD CLOUDS CLSD
  CNL COM COMM COMMERCIAL COMMISSIONED COMPACTED COMPLETE COMPLETED CONCRETE CONDITION
  CONDITIONS CONST CONSTRUCTION CONTACT CONTAMINATED CONTAMINATION CONTROL COORDINATE
  COORDINATED COORDINATES COR CORRECT CORRECTED CORRECTION CORRIDOR COURSE COVERED
  COVERING CREATED CREW CRFI CRITICAL CROSS CROSSING CTA CTC CTR CURFEW CURRENT
  CURRENTLY CYA CYD CYR DAILY DAMAGE DAMAGED DANGER DANGEROUS DATE DAY DAYLIGHT DAYS
  DEACTIVATED DEBRIS DEC DECEMBER DECLARED DECOMMISSIONED DEG DEGREE DEGREES DELAY
  DELAYED DELAYS DELETE DELETED DEP DEPARTURE DEPARTURES DEPENDENT DESCEND DESCENT
  DIRECTION DIRECTIONS DISPLACED DISTANCE DISTANCES DIVERSION DLA DME DRIFTING DRIFTS
  DRY DS DU DUE DURING DZ E EACH EAST EASTBOUND EASTERN EDGE EDGES EFF EFFECTIVE ELEV
  ELEVATION ELEVATIONS EMERG EMERGENCY EMS END ENDS ENE ENTIRE EQPT EQUIPMENT ERECTED
  ESE EST ESTIMATED EVENING EVERY EXC EXCEPT EXCL EXCLUDING EXERCISE EXERCISES EXPECT
  EXPECTED EXPIRED EXPIRES EXPIRY EXTENDED EXTENSION FAC FACILITIES FACILITY FADED FAIL
  FAILED FAILURE FEB FEBRUARY FEET FEW FG FINAL FIR FIRE FIREFIGHTING FIRST FIS FIX
  FIXED FL FLAGGED FLIGHTCHECK FLOW FLW FM FOD FOLLOWING FOOT FOR FORBIDDEN FOREIGN
  FREQ FREQUENCIES FREQUENCY FRI FRICTION FRIDAY FROM FROST FSS FT FU FUEL FUELER
  FUELING FUELLING FULL FULLY FURTHER FZDZ FZFG FZRA GATE GATES GBAS GEAR GLIDEPATH
  GLIDESLOPE GLS GMT GND GNSS GOOD GP GPS GR GRADIENT GRASS GRAVEL GREATER GRID GRIT
  GROOVED GROUND GS GUST GUSTING GUSTS H24 HAD HANGAR HANGARS HARD HAS HAVE HAZARD
  HAZARDOUS HAZARDS HEADING HEADINGS HEAVY HEIGHT HEIGHTS HEL HELI HELICOPTER HELIPAD
  HELIPORT HG HIGH HIGHER HIGHEST HIRL HJ HLD HLDG HN HOLD HOLDING HOLIDAY HOLIDAYS
  HOSPITAL HOUR HOURS HPA HR HRLY HRS HYDRANT HZ IAP IC ICE IDENT IDENTIFICATION IF IFR
  II III IIIA IIIB IIIC ILS IM IMC IMMEDIATE IMMEDIATELY IN INACTIVE INBOUND INCH INCL
  INCLUDING INCLUSIVE INDEPENDENT INFO INFORMATION INHG INITIAL INOP INOPERATIVE INSERT
  INSERTED INSIDE INSTALLED INSTRUMENT INT INTERSECTING INTERSECTION INTO INVALID IS
  ISSUANCE ISSUED ITEM ITEMS ITS IV JAN JANUARY JET JETA1 JETBLAST JUL JULY JUN JUNE
  KHZ KM KT KTS LANDING LANDINGS LASER LAST LATEST LATITUDE LDA LDG LEFT LENGTH LESS
  LEVEL LEVELS LGT LGTD LGTS LIFR LIGHT LIGHTED LIGHTING LIGHTS LIKELY LIMIT LIMITATION
  LIMITATIONS LIMITED LIMITS LINE LINES LIRL LNAV LOC LOCAL LOCALIZER LONGITUDE LOOSE
  LOW LOWER LOWEST LP LPV MAG MAGNETIC MAINT MAINTENANCE MALSF MALSR MANDATORY MAR
  MARCH MARKED MARKER MARKING MARKINGS MAST MAX MAXIMUM MAY MB MEASURED MEDEVAC MEDICAL
  MEDIUM MEN METAR METER METERS METRE METRES MF MHZ MIDDLE MIDNIGHT MILITARY MIN MINIMA
  MINIMUM MINIMUMS MINS MINUTE MINUTES MIRL MISSED MISSING MKR MLS MLW MM MNS MOBILE
  MOGAS MON MONDAY MONTH MORE MORNING MOVEMENT MRK MRKG MSL MTOW MUST MVFR N NAV NAVAID
  NAVAIDS NDB NE NEAR NEARBY NEW NEXT NIGHT NIGHTLY NIGHTS NIL NM NNE NNW NO NOISE NON
  NONMOVEMENT NONPRECISION NOON NORMAL NORTH NORTHBOUND NORTHERN NOT NOTAM NOTAMC
  NOTAMN NOTAMR NOTE NOTED NOTICE NOTICES NOV NOVEMBER NSC NUMBER NW OBJECT OBJECTS
  OBSERVED OBST OBSTACLE OBSTACLES OBSTRUCTION OBSTRUCTIONS OCT OCTOBER ODALS OF OFF
  OFFLINE OHD OLD OM OMIT OMITTED ON ONLINE ONLY ONTO OPEN OPENED OPENING OPERATE
  OPERATED OPERATES OPERATING OPERATION OPERATIONAL OPERATIONS OPERATIVE OPERATOR
  OPERATORS OPN OPPOSITE OPTIONAL OR ORIGINAL OTHER OTHERS OTS OUT OUTAGE OUTAGES
  OUTBOUND OUTSIDE OVC OVER OVERFLIGHT OVERFLY OVERFLYING OVERHEAD OVERRUN PAD PAGE
  PAINTED PAPI PARACHUTE PARACHUTING PARAJUMP PARALLEL PARKING PART PARTIAL PARTIALLY
  PARTS PATCHES PATCHY PATTERN PCT PER PERCENT PERIOD PERIODS PERM PERMANENT
  PERMANENTLY PERMITTED PERSONNEL PHONE PILOT PILOTS PIREP PL PLEASE PLOUGH PLOW
  PLOWING PLUS PO POINT POINTS POLE POOR PORTION PORTIONS POSITION POSITIONS POSSIBLE
  POSSIBLY POWER POWERLINE PPR PRECISION PREDICTED PREFERRED PRESENT PRESENTLY PREVIOUS
  PRIMARY PRIOR PRKG PROC PROCEDURE PROCEDURES PROCS PROGRESS PROHIBITED PROTECTED PSN
  PSR PUBLISH PUBLISHED PYLON QFE QNE QNH RA RADAR RADIAL RADIALS RADIO RADIUS RAIM
  RAMP RAMPS RCLL RECOMMENDED REF REFER REFERENCE REFERENCES REFERS REIL REMAIN
  REMAINDER REMAINING REMAINS REMOVAL REMOVED REOPEN REOPENED REOPENING REPLACE
  REPLACED REPORT REPORTED REPORTS REQUIRED REQUIREMENT REQUIREMENTS RESA RESCUE
  RESTORED RESTRICT RESTRICTED RESTRICTION RESTRICTIONS RESUME RESUMED RETURN RETURNED
  REVISE REVISED REVISION RFF RIGHT RNAV RNP ROTOR ROUTE ROUTES RPAS RSC RTHL RUNWAY
  RUNWAYS RVR RWY RWYCC RWYS S SA SAFETY SAME SAND SAT SATURDAY SAVING SAVINGS SCHED
  SCHEDULE SCHEDULED SCT SDF SE SEAPLANE SEASON SEASONAL SECONDARY SECTION SECTIONS
  SECTOR SEE SEEING SEGMENT SEGMENTS SELF SENSITIVE SEP SEPT SEPTEMBER SEQUENCE SERIES
  SERVE SERVICE SERVICEABLE SFC SFL SG SH SHALL SHORT SHORTEN SHORTENED SHOULD SHOULDER
  SHOULDERS SID SIDE SIDES SIDS SIGMET SIGN SIGNAGE SIGNS SIMULTANEOUS SKC SKED SKI
  SKID SLOT SLOTS SLUSH SM SN SNOW SNOWBANK SNOWBANKS SNOWTAM SOFT SOUTH SOUTHBOUND
  SOUTHERN SPECI SPECIAL SPRING SQ SR SS SSALR SSE SSR SSW STACK STAND STANDARD
  STANDING STANDS STAR STARS STOPBAR STOPBARS STOPWAY STOPWAYS STRAIGHT STRIP STRIPS
  SUBJECT SUCH SUMMER SUN SUNDAY SUNRISE SUNSET SUP SUPERSEDED SUPPLEMENT SUPPLEMENTS
  SUPS SURFACE SURFACES SUSPENDED SUSPENSION SVFR SW SWEEPING TACAN TAF TAIL TAKEOFF
  TAKEOFFS TAX TAXI TAXIING TAXILANE TAXILANES TAXIWAY TAXIWAYS TDZ TEL TELEPHONE TEMP
  TEMPO TEMPORARILY TEMPORARY TEST TESTING TEXT TFC THAN THAT THE THEIR THEM THEN THESE
  THEY THIS THOSE THR THRESHOLD THRESHOLDS THROUGH THRU THU THUR THURSDAY TIL TILL TIME
  TIMES TKOF TL TMA TO TODA TOP TORA TOW TOWARD TOWARDS TOWER TOWING TRACK TRAFFIC
  TRAINING TRANSITION TRANSITIONS TREE TREES TRIGGER TRUCK TRUE TS TUE TUES TUESDAY TWR
  TWY TWYS TXL U/S UAS UAV UFN UIR UNAUTHORISED UNAUTHORIZED UNAVAILABILITY UNAVAILABLE
  UNAVBL UNDER UNICOM UNIVERSAL UNLGTD UNLIGHTED UNLIKELY UNMARKED UNPAVED UNRELIABLE
  UNSERVICEABILITY UNSERVICEABLE UNTIL UNUSABLE UPDATE UPDATED UPON UPPER UREA USABLE
  USE USED USING UTC VA VALID VALIDITY VASI VEH VEHICLE VEHICLES VFR VIA VIC VICINITY
  VIS VISIBILITIES VISIBILITY VISUAL VMC VNAV VOR VORTAC VOT VRB W WAAS WARNING WAS
  WATER WAYPOINT WAYPOINTS WEATHER WED WEDNESDAY WEEKDAY WEEKDAYS WEEKEND WEEKENDS
  WEEKLY WEF WEIGHT WERE WEST WESTBOUND WESTERN WET WHEN WHENEVER WHERE WHILE WHOLE WI
  WIDTH WILL WIND WINDOW WINDOWS WINDROW WINDROWS WINDS WINGSPAN WINTER WIP WITH WITHIN
  WITHOUT WNW WORK WORKING WORKS WPT WSW WX YEAR YES ZONE ZONES ZULU
`;

export const AVIATION_TERMS: ReadonlySet<string> = new Set(
  TERM_SOURCE.split(/\s+/)
    .map((s) => s.toUpperCase())
    .filter((s) => s.length > 0)
);
